/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdint.h>
#include <timer.h>
#include <Ucglib.h>

static ucg_t   ucg;

int main(void)
{
	 SystemCoreClockUpdate();
	 TimerInit();
	 // Khởi tạo LCD
	 Ucglib4WireSWSPI_begin(&ucg, UCG_FONT_MODE_SOLID);
	 ucg_ClearScreen(&ucg);

	 ucg_SetFont(&ucg, ucg_font_profont15_mf); // lựa chon font chữ và cỡ chU
	 ucg_SetColor(&ucg, 0, 204, 102, 255);//MAU
	 ucg_SetColor(&ucg, 1, 0, 0, 0);
	 ucg_SetRotate180(&ucg);
	 ucg_DrawString (&ucg, 0 , 12 , 0, "Nhom 1 - TTCS"); // in dòng chữ ra LCD
//	 ucg_DrawString (&ucg, 0, 26, 0, "TTCS");
	 while(1)
	 {
		 processTimerScheduler();
	 }
}
